Repository aws/aws-sdk-net, pull requests merged in 2024-06, with the labels that each got.

#3293 Optimize `AWSSDKUtils.ToHex()` for speed and memory
  sdk/src/Core/AWSSDK.Core.NetStandard.csproj
  sdk/src/Core/Amazon.Util/AWSSDKUtils.cs
  sdk/src/Services/S3/Custom/Internal/AmazonS3ResponseHandler.cs
  sdk/test/NetStandard/UnitTests/AWSSDK.UnitTests.Custom.NetStandard.csproj
  sdk/test/NetStandard/UnitTests/Core/AWSSDKUtilsTests.cs
  sdk/test/UnitTests/Custom/Util/AWSSDKUtilsTests.cs
Labels: v4

#3335 Change version strategy in V4 to set AssemblyVersion
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/AssemblyInfo.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/AssemblyInfo.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/CoreAssemblyInfo.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/CoreAssemblyInfo.tt
Labels: v4

#3330 Add abstraction project for identity and auth
  docgenerator/SDKDocGeneratorLib/ReflectionWrappers.cs
  extensions/AWSSDK.Extensions.sln
  extensions/src/Smithy.Identity.Abstractions/BaseIdentity.cs
  extensions/src/Smithy.Identity.Abstractions/Properties/AssemblyInfo.cs
  extensions/src/Smithy.Identity.Abstractions/Smithy.Identity.Abstractions.csproj
  extensions/src/Smithy.Identity.Abstractions/smithy.abstractions.snk
  generator/ServiceClientGeneratorLib/GeneratorDriver.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/StructureGenerator.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/StructureGenerator.tt
  generator/ServiceClientGeneratorLib/SolutionFileCreator.cs
  sdk/AWSSDK.CoreAndCustomUnitTests.NetFramework.sln
  sdk/AWSSDK.CoreAndCustomUnitTests.NetStandard.sln
  sdk/AWSSDK.NetFramework.sln
  sdk/AWSSDK.NetStandard.sln
  sdk/src/Core/AWSSDK.Core.NetFramework.csproj
  sdk/src/Core/AWSSDK.Core.NetStandard.csproj
  sdk/src/Core/Amazon.Runtime/Credentials/AWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/RefreshingAWSCredentials.cs
  sdk/src/Services/CognitoIdentity/Generated/Model/Credentials.cs
  sdk/src/Services/SecurityToken/Generated/Model/Credentials.cs
  sdk/test/IntegrationTests/Tests/General.cs
Labels: v4, SRA

#3354 v4: Delete obsolete S3 Encryption client
  sdk/src/Core/Amazon.Runtime/Internal/ServiceClientHelpers.cs
  sdk/src/Core/Amazon.Runtime/SharedInterfaces/ICoreAmazonKMS.cs
  sdk/src/Core/Amazon.Runtime/SharedInterfaces/Internal/CoreAmazonKMS.cs
  sdk/src/Core/RuntimeDependencies/GlobalRuntimeDependencyRegistry.cs
  sdk/src/Services/KeyManagementService/Custom/AmazonKeyManagementServiceClient.Extension.cs
  sdk/src/Services/KeyManagementService/Custom/IAmazonKeyManagementService.Extension.cs
  sdk/src/Services/S3/Custom/Encryption/AmazonS3EncryptionClient.cs
  sdk/src/Services/S3/Custom/Encryption/CryptoConfiguration.cs
  sdk/src/Services/S3/Custom/Encryption/CryptoStorageMode.cs
  sdk/src/Services/S3/Custom/Encryption/EncryptionInstructions.cs
  sdk/src/Services/S3/Custom/Encryption/EncryptionMaterials.cs
  sdk/src/Services/S3/Custom/Encryption/EncryptionUtils.cs
  sdk/src/Services/S3/Custom/Encryption/Internal/SetupDecryptionHandler.cs
  sdk/src/Services/S3/Custom/Encryption/Internal/SetupEncryptionHandler.cs
  sdk/src/Services/S3/Custom/Encryption/Internal/UserAgentHandler.cs
  sdk/src/Services/S3/Custom/Encryption/UploadPartContextForEncryption.cs
  sdk/src/Services/S3/Custom/Model/InitiateMultipartUploadRequest.cs
  sdk/src/Services/S3/Custom/Transfer/Internal/_bcl+netstandard/UploadDirectoryCommand.cs
  sdk/test/NetStandard/IntegrationTests/IntegrationTests/S3/EncryptionTests.cs
  sdk/test/Services/S3/IntegrationTests/EncryptionInteropTest.cs
  sdk/test/Services/S3/IntegrationTests/EncryptionInteropTest.java
  sdk/test/Services/S3/IntegrationTests/EncryptionTests.cs
  sdk/test/Services/S3/IntegrationTests/S3ExpressTests.cs
  sdk/test/Services/S3/UnitTests/Custom/EncryptionChangeTest.cs
  sdk/test/UnitTests/Custom/Runtime/CustomResponses.cs
  sdk/test/UnitTests/Custom/Runtime/UnparseableResponsesTests.cs
  sdk/test/UnitTests/Custom/RuntimeDependencyRegistryTests.cs
Labels: v4

#3357 Remove the obsolete ActionIdentifiers in v4
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifier.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/AppStreamActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/AutoScalingActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/BillingActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudFormationActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudFrontActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudSearchActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudTrailActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudWatchActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CloudWatchLogsActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CognitoIdentityActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/CognitoSyncActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/DirectConnectActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/DynamoDBActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/EC2ActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ElastiCacheActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ElasticBeanstalkActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ElasticLoadBalancingActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ElasticMapReduceActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ElasticTranscoderActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/GlacierActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/IdentityandAccessManagementActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ImportExportActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/KinesisActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/MarketplaceActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/MarketplaceManagementPortalActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/MobileAnalyticsActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/OpsWorksActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/RDSActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/RedshiftActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/Route53ActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/S3ActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SESActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SNSActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SQSActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SecurityTokenServiceActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SimpleDBActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/SimpleWorkflowServiceActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/StorageGatewayActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/WhispersyncActionIdentifiers.cs
  sdk/src/Core/Amazon.Auth/AccessControlPolicy/ActionIdentifiers/ZocaloActionIdentifiers.cs
  sdk/src/Services/SQS/Custom/AmazonSQSClient.Extension.cs
  sdk/src/Services/SQS/Custom/_async/AmazonSQSClient.Extension.cs
  sdk/src/Services/SQS/Custom/_bcl/AmazonSQSClient.Extension.cs
  sdk/src/Services/SimpleNotificationService/Custom/AmazonSimpleNotificationServiceClient.Extensions.cs
  sdk/src/Services/SimpleNotificationService/Custom/_async/AmazonSimpleNotificationServiceClient.Extensions.cs
  sdk/src/Services/SimpleNotificationService/Custom/_bcl/AmazonSimpleNotificationServiceClient.Extensions.cs
  sdk/test/Services/DynamoDBv2/UnitTests/Custom/DynamoDBTests.cs
  sdk/test/Services/Lambda/IntegrationTests/LambdaTests.cs
  sdk/test/Services/S3/IntegrationTests/NotificationTests.cs
  sdk/test/UnitTests/Custom/PolicyTests.cs
  sdk/test/UnitTests/Custom/RegionEndpointTests.cs
Labels: v4

#3294 DynamoDB: add support for transactional writes that include update operations with custom update and condition expressions
  sdk/src/Services/DynamoDBv2/Custom/DataModel/TransactWrite.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DocumentTransactWrite.cs
  sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs
  sdk/test/Services/DynamoDBv2/IntegrationTests/DocumentTests.cs
Labels: dynamodb

#3353 V4 updates for AWSSDK.Extensions.NETCore.Setup (Native AOT)
  extensions/AWSSDK.Extensions.sln
  extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSOptions.cs
  extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSSDK.Extensions.NETCore.Setup.csproj
  extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSSDK.Extensions.NETCore.Setup.nuspec
  extensions/src/AWSSDK.Extensions.NETCore.Setup/ClientFactory.cs
  extensions/src/AWSSDK.Extensions.NETCore.Setup/ConfigurationExtensions.cs
  extensions/src/AWSSDK.Extensions.NETCore.Setup/DefaultClientConfig.cs
  extensions/src/AWSSDK.Extensions.NETCore.Setup/InternalConstants.cs
  extensions/src/AWSSDK.Extensions.NETCore.Setup/Schema/AWSSDK.Extensions.NETCore.Setup.targets
  extensions/src/AWSSDK.Extensions.NETCore.Setup/Schema/ConfigurationSchema.json
  extensions/src/AWSSDK.Extensions.NETCore.Setup/ServiceCollectionExtensions.cs
  extensions/test/NETCore.SetupTests/ConfigurationTests.cs
  extensions/test/NETCore.SetupTests/MockServiceClasses.cs
  extensions/test/NETCore.SetupTests/NETCore.SetupTests.csproj
  extensions/test/NETCore.SetupTests/TestFiles/MockServiceClientConfigTest.json
  generator/ServiceClientGeneratorLib/Generators/ProjectFiles/VS2017ProjectFile.cs
  generator/ServiceClientGeneratorLib/Generators/ProjectFiles/VS2017ProjectFile.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.tt
  sdk/src/Core/AWSSDK.Core.NetStandard.csproj
  sdk/src/Core/Amazon.Runtime/ClientConfig.cs
  sdk/src/Core/Amazon.Runtime/IAmazonService.cs
  sdk/test/NetStandard/UnitTests/ClientConfigTests.cs
Labels: aot, v4

#3358 Revert "Add abstraction project for identity and auth"
  docgenerator/SDKDocGeneratorLib/ReflectionWrappers.cs
  extensions/AWSSDK.Extensions.sln
  extensions/src/Smithy.Identity.Abstractions/BaseIdentity.cs
  extensions/src/Smithy.Identity.Abstractions/Properties/AssemblyInfo.cs
  extensions/src/Smithy.Identity.Abstractions/Smithy.Identity.Abstractions.csproj
  extensions/src/Smithy.Identity.Abstractions/smithy.abstractions.snk
  generator/ServiceClientGeneratorLib/GeneratorDriver.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/StructureGenerator.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/StructureGenerator.tt
  generator/ServiceClientGeneratorLib/SolutionFileCreator.cs
  sdk/AWSSDK.CoreAndCustomUnitTests.NetFramework.sln
  sdk/AWSSDK.CoreAndCustomUnitTests.NetStandard.sln
  sdk/AWSSDK.NetFramework.sln
  sdk/AWSSDK.NetStandard.sln
  sdk/src/Core/AWSSDK.Core.NetFramework.csproj
  sdk/src/Core/AWSSDK.Core.NetStandard.csproj
  sdk/src/Core/Amazon.Runtime/Credentials/AWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/RefreshingAWSCredentials.cs
  sdk/src/Services/CognitoIdentity/Generated/Model/Credentials.cs
  sdk/src/Services/SecurityToken/Generated/Model/Credentials.cs
  sdk/test/IntegrationTests/Tests/General.cs
Labels: v4

#3324 Optimize AWS4Signer
  sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs
  sdk/src/Core/Amazon.Util/AWSSDKUtils.cs
  sdk/src/Core/ThirdParty/RuntimeBackports/ValueStringBuilder.cs
  sdk/test/NetStandard/UnitTests/Core/AWS4SignerTests.cs
  sdk/test/NetStandard/UnitTests/Core/AWSSDKUtilsTests.cs
Labels: v4
