Repository aws/aws-sdk-net, pull requests merged in 2025-04, with the labels that each got.

#3736 [SRA] Remove AWSSignerType attribute from service configs
  generator/.DevConfigs/3388e8f1-17fe-40f7-bcf3-bb43641e5f7a.json
  generator/ServiceClientGeneratorLib/Generators/Endpoints/EndpointResolver.partial.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceConfig.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceConfig.tt
  sdk/src/Core/Amazon.Runtime/Credentials/Internal/AuthSchemeOption.cs
  sdk/src/Core/Amazon.Runtime/Internal/AWSSignerTypeAttribute.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CSMHandler/CSMCallAttemptHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/EndpointDiscoveryHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Signer.cs
  sdk/test/UnitTests/Custom/Runtime/EndpointDiscoveryTests.cs
Labels: v4, SRA

#3740 Updates to handle protocolSettings h2 optional.
  generator/ServiceClientGeneratorLib/Generators/Marshallers/AWSQueryRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/AWSQueryRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/Marshallers/JsonRPCRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/JsonRPCRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/Marshallers/RestXmlRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/RestXmlRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetFramework.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetFramework.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetStandard.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetStandard.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetFramework.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetFramework.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.tt
  generator/ServiceClientGeneratorLib/Operation.cs
Labels: v4

#3737 Changed the default value of SSOAWSCredentialsOptions.SupportsGettingNewToken as false and improved error messaging if required SSO options are missing while generating new credentials.
  generator/.DevConfigs/b39b85e0-42cc-4aac-a699-8dd1795a5fb0.json
  sdk/src/Core/Amazon.Runtime/Credentials/Internal/_bcl+netstandard/SSOTokenManager.cs
  sdk/src/Core/Amazon.Runtime/Credentials/_bcl+netstandard/SSOAWSCredentialsOptions.cs
Labels: v4

#3738 Business metrics tracking UA 2.1
  generator/.DevConfigs/a069861d-cd92-4d43-b45b-3aa11112a39b.json
  generator/ServiceModels/s3/s3.customizations.json
  sdk/src/Core/Amazon.Runtime/AmazonWebServiceRequest.cs
  sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs
  sdk/src/Core/Amazon.Runtime/Credentials/AWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleWithWebIdentityCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/BasicAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/DefaultInstanceProfileAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/EnvironmentVariablesAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/FederatedAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/GenericContainerCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/ProcessAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/SessionAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/_bcl+netstandard/SSOAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/Credentials/_bcl/AppConfigAWSCredentials.cs
  sdk/src/Core/Amazon.Runtime/IClientConfig.cs
  sdk/src/Core/Amazon.Runtime/Internal/IAmazonWebServiceRequest.cs
  sdk/src/Core/Amazon.Runtime/Internal/UserAgent/UserAgentDetails.cs
  sdk/src/Core/Amazon.Runtime/Internal/UserAgent/UserAgentFeatureId.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Contexts.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/BaseAuthResolverHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/BaseEndpointResolver.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/ChecksumHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CompressionHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Marshaller.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Signer.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryHandler.cs
  sdk/src/Core/Amazon.Runtime/_bcl+netstandard/PaginatorUtils.cs
  sdk/src/Core/Amazon.Util/Internal/InternalSDKUtils.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DocumentBatchGet.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DocumentBatchWrite.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DocumentTransactGet.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DocumentTransactWrite.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Search.cs
  sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs
  sdk/src/Services/Glacier/Custom/Transfer/ArchiveTransferManager.cs
  sdk/src/Services/S3/Custom/Internal/AmazonS3PostMarshallHandler.cs
  sdk/src/Services/S3/Custom/Internal/AmazonS3UserAgentHandler.cs
  sdk/src/Services/S3/Custom/Transfer/Internal/BaseCommand.cs
  sdk/src/Services/S3/Custom/Transfer/Internal/_async/MultipartUploadCommand.async.cs
  sdk/src/Services/S3/Custom/_bcl/IO/S3Helper.cs
  sdk/src/Services/S3/Generated/_bcl/AmazonS3Client.cs
  sdk/src/Services/S3/Generated/_netstandard/AmazonS3Client.cs
  sdk/src/Services/SSOOIDC/Custom/Internal/_bcl+netstandard/CoreAmazonSSOOIDC.cs
  sdk/test/Services/S3/UnitTests/Custom/UserAgentTests.cs
  sdk/test/UnitTests/Custom/AWSSDK.UnitTestUtilities.NetFramework.csproj
  sdk/test/UnitTests/Custom/AWSSDK.UnitTestUtilities.NetStandard.csproj
  sdk/test/UnitTests/Custom/EndpointsTests.cs
  sdk/test/UnitTests/Custom/Runtime/UserAgentTests.cs
  sdk/test/UnitTests/Custom/Runtime/_bcl/PaginatorUserAgentTest.cs
Labels: v4

#3743 [V4] Preview 12
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/AWSSDK.Extensions.Bedrock.MEAI.nuspec
  extensions/src/AWSSDK.Extensions.CloudFront.Signers/AWSSDK.Extensions.CloudFront.Signers.nuspec
  extensions/src/AWSSDK.Extensions.CrtIntegration/AWSSDK.Extensions.CrtIntegration.nuspec
  extensions/src/AWSSDK.Extensions.EC2.DecryptPassword/AWSSDK.Extensions.EC2.DecryptPassword.nuspec
  extensions/src/AWSSDK.Extensions.Logging.ILoggerAdaptor/AWSSDK.Extensions.Logging.ILoggerAdaptor.nuspec
  extensions/src/AWSSDK.Extensions.Logging.Log4NetAdaptor/AWSSDK.Extensions.Logging.Log4NetAdaptor.nuspec
  extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSSDK.Extensions.NETCore.Setup.nuspec
  generator/.DevConfigs/3388e8f1-17fe-40f7-bcf3-bb43641e5f7a.json
  generator/.DevConfigs/62a70097-c6d6-4566-907b-20b48b2764d4.json
  generator/.DevConfigs/8a48524d-da8b-4c04-b57e-ad196a51debb.json
  generator/.DevConfigs/EB610C98-C25D-4701-AC36-C92D241CC20F.json
  generator/.DevConfigs/a069861d-cd92-4d43-b45b-3aa11112a39b.json
  generator/.DevConfigs/b39b85e0-42cc-4aac-a699-8dd1795a5fb0.json
  generator/.DevConfigs/f628f7f0-c5db-4d84-bd89-83fd57275216.json
  generator/ServiceModels/_sdk-versions.json
Labels: v4

#3735 Issues/2576 dynamo db entry conversion
  generator/.DevConfigs/e5fd3631-e192-4dcb-931b-69d45722ae02.json
  sdk/src/Services/DynamoDBv2/Custom/Conversion/DynamoDBEntryConversion.cs
  sdk/src/Services/DynamoDBv2/Custom/DataModel/Attributes.cs
  sdk/src/Services/DynamoDBv2/Custom/DataModel/Configs.cs
  sdk/src/Services/DynamoDBv2/Custom/DataModel/InternalModel.cs
  sdk/test/Services/DynamoDBv2/IntegrationTests/DataModelTests.cs
Labels: v4

#3747 Update auth resolver async flow to add user agent details after resolving identity
  generator/.DevConfigs/9c63240f-0f30-4c8e-b0a7-e434529126fd.json
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/BaseAuthResolverHandler.cs
Labels: v4, SRA

#3746 Update protocol test generator to generate error response tests. Don't do case sensitive header lookups in tests.
  generator/.DevConfigs/c1bcdcb3-ce85-4cc9-829b-7cea143ae236.json
  generator/ProtocolTestsGenerator/smithy-dotnet-codegen/src/main/java/software/amazon/smithy/dotnet/codegen/HttpProtocolTestGenerator.java
  sdk/test/ProtocolTests/Generated/EC2Protocol/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/ProtocolTests/Generated/JSONRPC10/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/ProtocolTests/Generated/JsonProtocol/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/ProtocolTests/Generated/QueryProtocol/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/ProtocolTests/Generated/RestJsonProtocol/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/ProtocolTests/Generated/RestXmlProtocol/dotnet-protocol-test-codegen/GreetingWithErrors.cs
  sdk/test/UnitTests/Custom/TestTools/WebResponseData.cs
Labels: v4

#3752 Remove dead .NET Framework 3.5 code
  generator/.DevConfigs/9EB387DE-2F05-4D61-9414-357109AC3055.json
  sdk/src/Core/Amazon.Runtime/Pipeline/Contexts.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/_bcl/RuntimeAsyncResult.cs
  sdk/src/Core/GlobalSuppressions.cs
  sdk/test/ProtocolTests/Custom/ProtocolTestUtils.cs
  sdk/test/Services/S3/UnitTests/Custom/S3ArnTestUtils.cs
  sdk/test/UnitTests/Custom/Mocking/TestUtils.cs
  sdk/test/UnitTests/Custom/Runtime/HttpHandlerTests.cs
  sdk/test/UnitTests/Custom/Runtime/RuntimePipelineTestBase.cs
Labels: v4

#3753 [V4] Update SDK to respect Profile property set in the client config when resolving credentials
  generator/.DevConfigs/1d61d247-5e88-4613-a97f-ee94ef9ff8fd.json
  sdk/src/Core/Amazon.Runtime/Credentials/AnonymousIdentityResolver.cs
  sdk/src/Core/Amazon.Runtime/Credentials/DefaultAWSCredentialsIdentityResolver.cs
  sdk/src/Core/Amazon.Runtime/Credentials/DefaultAWSTokenIdentityResolver.cs
  sdk/src/Core/Amazon.Runtime/Credentials/Internal/DefaultIdentityResolverConfiguration.cs
  sdk/src/Core/Amazon.Runtime/IClientConfig.cs
  sdk/src/Core/Amazon.Runtime/Identity/IIdentityResolver.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/BaseAuthResolverHandler.cs
  sdk/src/Core/Profile.cs
  sdk/test/Services/DSQL/UnitTests/Custom/DSQLAuthTokenGeneratorTest.cs
  sdk/test/Services/RDS/UnitTests/Custom/RDSAuthTokenGeneratorTest.cs
  sdk/test/UnitTests/AWSSDK.UnitTests.Custom.NetFramework.csproj
  sdk/test/UnitTests/Custom/Runtime/Credentials/AccountIdEndpointTests/AccountIdBasedEndpointsTest.cs
  sdk/test/UnitTests/Custom/Runtime/Credentials/AccountIdEndpointTests/accountid-source-testcases.json
  sdk/test/UnitTests/Custom/Runtime/Credentials/DefaultCredentialsResolverTests.cs
Labels: v4

#3748 Update to M.E.AI 9.4.0-preview.1.25207.5
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/AWSSDK.Extensions.Bedrock.MEAI.NetFramework.csproj
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/AWSSDK.Extensions.Bedrock.MEAI.NetStandard.csproj
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/AWSSDK.Extensions.Bedrock.MEAI.nuspec
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/BedrockChatClient.cs
  extensions/src/AWSSDK.Extensions.Bedrock.MEAI/BedrockEmbeddingGenerator.cs
  extensions/test/BedrockMEAITests/BedrockChatClientTests.cs
  extensions/test/BedrockMEAITests/BedrockEmbeddingGeneratorTests.cs
  extensions/test/BedrockMEAITests/BedrockMEAITests.NetFramework.csproj
Labels: v4

#3760 Add observability feature IDs to User Agent header
  generator/.DevConfigs/7d427a71-cb57-42d2-89db-f5b08b5fb559.json
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/CoreAssemblyInfo.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/CoreAssemblyInfo.tt
  sdk/src/Core/Amazon.Runtime/Internal/UserAgent/UserAgentFeatureId.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Marshaller.cs
  sdk/src/Core/Properties/AssemblyInfo.cs
  sdk/test/UnitTests/Custom/AWSSDK.UnitTestUtilities.NetFramework.csproj
  sdk/test/UnitTests/Custom/AWSSDK.UnitTestUtilities.NetStandard.csproj
  sdk/test/UnitTests/Custom/Runtime/UserAgentTests.cs
Labels: v4

#3755 Fix: Allow some sso properties to be used in conjunction with source_profile and credential_source
  generator/.DevConfigs/b24980c4-b6f6-4181-9789-fda85df054a3.json
  sdk/src/Core/Amazon.Runtime/CredentialManagement/Internal/CredentialProfileTypeDetector.cs
  sdk/test/UnitTests/Custom/Runtime/Credentials/AWSCredentialsFactoryTest.cs
Labels: v4

#3757 Enable MockHttpRequestFactory in non Net Framework targets
  sdk/test/UnitTests/Custom/Runtime/CustomResponses.cs
  sdk/test/UnitTests/Custom/Runtime/HttpHandlerTests.cs
  sdk/test/UnitTests/Custom/TestTools/MockWebResponse.cs
Labels: v4

#3767 [V4] Update generator to handle paginators where the token is a collection
  generator/.DevConfigs/50736c58-f72b-4e62-8cc1-b7b7b8f11f0a.json
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/BasePaginator.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/BasePaginator.tt
  sdk/src/Core/AWSConfigs.cs
  sdk/src/Services/DynamoDBv2/Generated/Model/_bcl+netstandard/BatchGetItemPaginator.cs
  sdk/src/Services/DynamoDBv2/Generated/Model/_bcl+netstandard/QueryPaginator.cs
  sdk/src/Services/DynamoDBv2/Generated/Model/_bcl+netstandard/ScanPaginator.cs
Labels: v4

#3763 Fix User-Agent duplication and support case-sensitive constant classes for feature IDs
  generator/.DevConfigs/6ea8698f-8d5d-4a79-8648-42451415f12e.json
  sdk/src/Core/Amazon.Runtime/ConstantClass.cs
  sdk/src/Core/Amazon.Runtime/Internal/UserAgent/UserAgentDetails.cs
  sdk/src/Core/Amazon.Runtime/Internal/UserAgent/UserAgentFeatureId.cs
  sdk/src/Core/Amazon.Runtime/Pipeline/Contexts.cs
  sdk/test/UnitTests/Custom/Runtime/UserAgentTests.cs
Labels: v4

#3779 Add check for H2Support == H2SupportDegree.Optional for specification compliance.
  generator/ServiceClientGeneratorLib/Generators/Marshallers/AWSQueryRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/AWSQueryRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/Marshallers/JsonRPCRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/JsonRPCRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/Marshallers/RestXmlRequestMarshaller.cs
  generator/ServiceClientGeneratorLib/Generators/Marshallers/RestXmlRequestMarshaller.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetFramework.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetFramework.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetStandard.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceClientsNetStandard.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetFramework.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetFramework.tt
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.cs
  generator/ServiceClientGeneratorLib/Generators/SourceFiles/ServiceInterfaceNetStandard.tt
Labels: v4

#3778 Add check for H2Support == H2SupportDegree.Optional for specification compliance.
  generator/ServiceClientGeneratorLib/ServiceModel.cs
Labels: v3
