Repository aws/aws-sdk-net, pull requests merged in 2025-05, with the labels that each got.

#3798 [V3] Add note about OpenSSL 3 limitation for CloudFront signers
  generator/.DevConfigs/0878551f-ba20-4400-84fc-7892b9487368.json
  sdk/src/Services/CloudFront/Custom/AmazonCloudFrontCookieSigner.cs
  sdk/src/Services/CloudFront/Custom/AmazonCloudFrontUrlSigner.cs
Labels: v3

#3830 Fix: Do not overwrite content-type header if explicitly set in multip…
  generator/.DevConfigs/6817cff6-2165-4dbb-ad6e-30d0f34fd3dc.json
  sdk/src/Services/S3/Custom/Transfer/Internal/MultipartUploadCommand.cs
  sdk/test/Services/S3/IntegrationTests/TransferUtilityTests.cs
Labels: v3

#3829 Do not overwrite content-type header if set explicitly in MPU scenarios
  generator/.DevConfigs/c07cc471-4e94-42cf-9c2f-c8c3fa906465.json
  sdk/src/Services/S3/Custom/Transfer/Internal/MultipartUploadCommand.cs
  sdk/test/Services/S3/IntegrationTests/TransferUtilityTests.cs
Labels: v4

#3841 Fix Multipart upload command cancellation
  generator/.DevConfigs/da5f5892-75e9-425e-8dd6-4ae3cda8530a.json
  sdk/src/Services/S3/Custom/Transfer/Internal/_async/MultipartUploadCommand.async.cs
Labels: bug, s3, p2, v4
